service: headless-serverless

provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  versionFunctions: false
  profile: digitally
  timeout: 120
package:
 exclude:
    - node_modules/electron/dist/**
functions:
  nightmare:
    memorySize: 384
    handler: nightmare.execute
    events:
      - http:
        path: nightmare
        method: post
  horseman:
      memorySize: 384
      handler: horseman.execute
      events:
        - http:
          path: horseman
          method: post
